name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: seeder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: seeder/Dockerfile
          push: true
          tags: ghcr.io/toyz/ffxiv-tools/seeder:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: tracker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: tracker/Dockerfile
          push: true
          tags: ghcr.io/toyz/ffxiv-tools/tracker:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: patch_server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: patch_server/Dockerfile
          push: true
          tags: ghcr.io/toyz/ffxiv-tools/patch_server:latest
          labels: ${{ steps.meta.outputs.labels }}
