name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: seeder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: seeder/Dockerfile
          push: true
          tags: seeder
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: tracker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: seeder/Dockerfile
          push: true
          tags: tracker
          labels: ${{ steps.meta.outputs.labels }}
